version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-api
    ports:
        - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
  worker:
    build: 
      context: .
      dockerfile: Dockerfile-worker
    image: node:lts-alpine
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    command: mongod --smallfiles --logpath=/dev/null --quiet